add typings
Mametaro-discord/discord-slash-commands-v12 pull request #21
Opened 2021-11-24 09:40 UTC by waki285

まだdraftなんでマージしないでね

2021-11-26 11:33 UTC, waki285 commented
@Mametaro-discord 
準備ができたからレビューお願い。とりあえず絶対に **めんどくさいなー、全部あってるやろ、Approveﾎﾟﾁｰ**とかはしないでね、わかってない部分、TODOの部分があるから絶対にRequested Changesになるはずだから。

2021-11-26 13:57 UTC, kage-sakura commented
send, edit系のメソッドについて。

`content` には以下のような実引数を指定することも可能なので、`StringResolvable | APIMessage` だけでは足りないかと。
```js
.sendMessage({
  embed: new MessageEmbed()
         .setTitle('XXX')
})

2021-11-26 14:06 UTC, kage-sakura commented on typings/index.d.ts
> +  delete(): Promise<void>;
```suggestion
  delete(): Promise<Reply>;
```

2021-11-26 14:20 UTC, kage-sakura commented on typings/index.d.ts
> +export type	ApplicationCommandOptionsChoices = {
```suggestion
export type ApplicationCommandOptionsChoices = {
```

2021-11-26 14:23 UTC, kage-sakura commented on typings/index.d.ts
> +  add(data: ApplicationCommandData, cache:boolean, guildId: unknown): {};
```suggestion
  add(data: ApplicationCommandData, cache:boolean, guildId: Snowflake): {}; 
```

2021-11-26 14:33 UTC, Mametaro-discord commented
> @Mametaro-discord
> 準備ができたからレビューお願い。とりあえず絶対に **めんどくさいなー、全部あってるやろ、Approveﾎﾟﾁｰ**とかはしないでね、わかってない部分、TODOの部分があるから絶対にRequested Changesになるはずだから。

こんなやってもらったんやからそんなことしないさ！
サンガツ！

2021-11-26 14:39 UTC, kage-sakura commented on typings/index.d.ts
> +  fetchMessage(message: string): Promise<APIMessage>;
戻り値が違う気がします。(間違っていたらごめんなさい)

2021-11-27 00:33 UTC, waki285 commented on typings/index.d.ts
> +export type	ApplicationCommandOptionsChoices = {
なんでこんなスペース開いてたんだ...?

2021-11-27 00:34 UTC, waki285 commented on typings/index.d.ts
> +  add(data: ApplicationCommandData, cache:boolean, guildId: unknown): {};
![Screenshot 2021-11-27 09 34 12](https://user-images.githubusercontent.com/67305123/143662593-ed2311ef-d187-48b2-abfe-b2959077c0ea.png)
ここ、unknownにしないとなぜかエラーになるんや...

2021-11-27 00:38 UTC, waki285 commented on typings/index.d.ts
> +  fetchMessage(message: string): Promise<APIMessage>;
Webhookって送信した後は204返した覚えがあって、deleteも204返すと思ってたので、どこが違うのか教えてもらうことはできますか？

2021-11-27 01:34 UTC, kage-sakura commented on typings/index.d.ts
> +  fetchMessage(message: string): Promise<APIMessage>;
現段階では、sendMessageとdeleteMessageはPromise\<Buffer\>を、editMessageとfetchMessageはPromsise\<Object\>を返します。
https://github.com/Mametaro-discord/discord-slash-commands-v12/blob/master/src/structures/ExtendedWebhookClient.js#L14-L107

2021-11-27 02:22 UTC, waki285 commented on typings/index.d.ts
> +  fetchMessage(message: string): Promise<APIMessage>;
```suggestion
  sendMessage(content: StringResolvable | APIMessage, options: unknown): Promise<void>;
  editMessage(message: string, content: StringResolvable | APIMessage, options: unknown): Promise<Object>;
  deleteMessage(message: string): Promise<void>;
  fetchMessage(message: string): Promise<Object>;
```
変えておきます

2021-11-27 02:42 UTC, kage-sakura commented on typings/index.d.ts
> +  add(data: ApplicationCommandData, cache:boolean, guildId: unknown): {};
こんなのはどうでしょうか。
```suggestion
declare class OverridableManager<V, K, R> extends BaseManager<V, K, R> {
  public add(...args: any[]): any;
}

export class ApplicationCommandManager extends OverridableManager<Snowflake, ApplicationCommand, ApplicationCommandResolvable> {
  protected constructor(client: Client, iterable: Array<any>);
  get permissions(): ApplicationCommandPermissionsManager;
  add(data: ApplicationCommandData, cache:boolean, guildId: Snowflake): ApplicationCommand; 
```

変更内容
・https://github.com/discordjs/discord.js/blob/v12/typings/index.d.ts#L1982-L1985 を真似て、OverridableManagerを作ってそれを継承するようにしてみました。
・`ApplicationCommandManager` の親クラスを `OverridableManager<Snowflake, ApplicationCommand, ApplicationCommandResolvable>` に変更しました。
・コンストラクーの第２引数 `iterable` の型を `Array<"Structure">` から `Array<any>` に変更しました。
・コンストラクターの第３引数 `holds` が未使用であり、かつ、不必要だと判断したため、削除しました。
・ApplicationCommandManager#addの戻り値の型を `{}` から `ApplicationCommand` に変更しました。

2021-11-27 08:14 UTC, waki285 commented on typings/index.d.ts
> +  add(data: ApplicationCommandData, cache:boolean, guildId: unknown): {};
有能

2021-11-28 02:04 UTC, Mametaro-discord requested changes, later dismissed
みてみた

2021-12-02 11:11 UTC, Mametaro-discord requested changes
新レビュー
復活

2021-12-11 16:34 UTC, kage-sakura commented on typings/index.d.ts
> +}
ApplicationCommand#patch によって追加されるプロパティが足りない気がします。

2025-03-23 06:41 UTC, closed without merging